'use client';
import {useMemo,useState} from 'react';

const products=[
 {name:'Imprint Ring',material:'Recycled silver',price:9800,kind:'Rings',tone:'silver'},
 {name:'Fold Hoops',material:'Gold vermeil',price:13200,kind:'Earrings',tone:'gold'},
 {name:'Trace Pendant',material:'14k gold',price:37800,kind:'Necklaces',tone:'gold'},
 {name:'Pressure Cuff',material:'Recycled silver',price:17400,kind:'Bracelets',tone:'silver'},
 {name:'Contour Ring',material:'Gold vermeil',price:11600,kind:'Rings',tone:'gold'},
 {name:'Held Pearl Earrings',material:'Freshwater pearl · vermeil',price:15900,kind:'Earrings',tone:'pearl'},
 {name:'Tide Line Chain',material:'14k gold',price:42500,kind:'Necklaces',tone:'gold'},
 {name:'Soft Edge Bangle',material:'Recycled silver',price:18800,kind:'Bracelets',tone:'silver'},
];
const peso=(n:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(n);
type Product=typeof products[number];

export default function Storefront({view='home'}:{view?:string}){
 const [cart,setCart]=useState<Product[]>([]),[wish,setWish]=useState<string[]>([]),[drawer,setDrawer]=useState<'menu'|'search'|'cart'|null>(null),[query,setQuery]=useState(''),[notice,setNotice]=useState('');
 const [sort,setSort]=useState('featured'),[filter,setFilter]=useState('All');
 const shown=useMemo(()=>{let x=filter==='All'?products:products.filter(p=>p.kind.toLowerCase()===filter.toLowerCase()||p.material.toLowerCase().includes(filter.toLowerCase()));if(query)x=x.filter(p=>(p.name+p.kind+p.material).toLowerCase().includes(query.toLowerCase()));return [...x].sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:0)},[filter,query,sort]);
 const add=(p:Product)=>{setCart(x=>[...x,p]);setNotice(`${p.name} added to your bag`);setTimeout(()=>setNotice(''),2400)};
 const toggleWish=(p:Product)=>setWish(x=>x.includes(p.name)?x.filter(n=>n!==p.name):[...x,p.name]);
 const routeTitle:Record<string,string>={shop:'Shop all jewelry',rings:'Rings',earrings:'Earrings',necklaces:'Necklaces',bracelets:'Bracelets',new:'New arrivals','fine-jewelry':'Fine jewelry','gift-cards':'Gift cards',wishlist:'Your wishlist',search:'Search Ursula',story:'Our story',craftsmanship:'Made slowly. Worn instinctively.',materials:'Materials & responsibility',journal:'The Ursula journal',appointments:'Virtual styling',personalization:'Personalization studio',care:'Jewelry care',repairs:'Repairs & warranty',shipping:'Shipping & returns',faq:'Frequently asked questions',contact:'Client care',account:'Your account',checkout:'Secure checkout'};
 const catalog=['shop','rings','earrings','necklaces','bracelets','new','fine-jewelry','collections','impression'].includes(view);
 return <div id="top"><a className="skip" href="#main">Skip to content</a><div className="announcement">Complimentary nationwide shipping on orders over ₱8,000 · 14-day returns</div>
  <header className="site-header"><button className="menu-button" onClick={()=>setDrawer('menu')} aria-label="Open menu">☰</button><nav aria-label="Primary navigation"><a href="/shop">Shop</a><a href="/new">New</a><a href="/collections">Collections</a><a href="/personalization">Personalize</a><a href="/journal">Journal</a></nav><a className="wordmark" href="/" aria-label="Ursula home">URSULA</a><div className="header-actions"><button onClick={()=>setDrawer('search')} aria-label="Search">⌕</button><a href="/account">Account</a><a href="/wishlist">♡ {wish.length||''}</a><button onClick={()=>setDrawer('cart')}>Bag · {cart.length}</button></div></header>
  {view==='home'?<Home add={add} wish={wish} toggleWish={toggleWish}/>:catalog?<Catalog title={routeTitle[view]||'The Impression Collection'} products={shown} filter={filter} setFilter={setFilter} sort={sort} setSort={setSort} add={add} wish={wish} toggleWish={toggleWish}/>:<ContentPage view={view} title={routeTitle[view]||view.replaceAll('-',' ')} products={products} add={add} wish={wish} toggleWish={toggleWish}/>}<Footer/>{notice&&<div className="toast" role="status">{notice}</div>}
  {drawer&&<div className="drawer-backdrop" onMouseDown={()=>setDrawer(null)}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setDrawer(null)} aria-label="Close">×</button>{drawer==='menu'&&<><p className="eyebrow">Menu</p><div className="drawer-links"><a href="/shop">Shop all</a><a href="/new">New arrivals</a><a href="/rings">Rings</a><a href="/earrings">Earrings</a><a href="/necklaces">Necklaces</a><a href="/bracelets">Bracelets</a><a href="/story">Our story</a></div></>}{drawer==='search'&&<><p className="eyebrow">Search Ursula</p><h2>What are you looking for?</h2><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try ‘silver ring’"/>{query&&<div className="search-results">{shown.length?shown.slice(0,4).map(p=><a key={p.name} href="/shop">{p.name}<span>{peso(p.price)}</span></a>):<p>No pieces found. Try “ring” or “gold”.</p>}</div>}</>}{drawer==='cart'&&<><p className="eyebrow">Your bag</p><h2>{cart.length?`${cart.length} piece${cart.length>1?'s':''}`:'Your bag is waiting'}</h2>{cart.map((p,i)=><div className="bag-row" key={i}><ProductArt tone={p.tone}/><span>{p.name}<small>{peso(p.price)}</small></span></div>)}{cart.length>0&&<><div className="bag-total"><span>Subtotal</span><b>{peso(cart.reduce((s,p)=>s+p.price,0))}</b></div><a className="button button-primary full" href="/checkout">Checkout securely</a><p className="microcopy">Taxes included. Free nationwide shipping.</p></>}</>}</aside></div>}
 </div>}

function Home({add,wish,toggleWish}:{add:(p:Product)=>void,wish:string[],toggleWish:(p:Product)=>void}){return <main id="main"><section className="hero"><video className="hero-video" autoPlay muted loop playsInline preload="metadata" poster="/ursula-hero-poster.jpg" aria-hidden="true"><source src="/ursula-hero.mp4" type="video/mp4"/></video><div className="hero-image" role="img" aria-label="Sculptural gold and silver jewelry in warm studio light"/><div className="hero-copy"><p className="eyebrow">The Impression Collection</p><h1>Jewelry shaped<br/>by instinct.</h1><p>Sculptural forms made to hold memory, movement, and meaning.</p><div className="hero-buttons"><a className="button button-primary" href="/collections/impression">Explore the collection</a><a className="button button-secondary" href="/new">Shop new arrivals</a></div></div></section><section className="trust-strip"><span>Responsibly made</span><span>Five-year warranty</span><span>Secure local checkout</span><span>Easy 14-day returns</span></section><Categories/><ProductSection title="New forms" kicker="Just arrived" products={products.slice(0,4)} add={add} wish={wish} toggleWish={toggleWish}/><section className="split-story" id="collection"><div className="story-image portrait-one"/><div className="story-copy"><p className="eyebrow">The Impression Collection</p><h2>Metal remembers.</h2><p>A study in softness, pressure, and permanence—designed in Manila and made by specialist hands.</p><a className="text-link" href="/collections/impression">Enter the collection →</a></div></section><section className="split-story reverse"><div className="story-copy"><p className="eyebrow">Our craft</p><h2>Made slowly.<br/>Worn instinctively.</h2><p>Recycled precious metals. Hand-finished surfaces. Shapes that carry the trace of human hands.</p><a className="text-link" href="/craftsmanship">Discover our craft →</a></div><div className="story-image craft-image"/></section><ProductSection title="Best sellers" kicker="Loved across the Philippines" products={products.slice(4)} add={add} wish={wish} toggleWish={toggleWish}/><section className="assurance"><div><b>Recycled precious metals</b><span>Chosen for a lighter footprint</span></div><div><b>Hand-finished in small batches</b><span>Made with considered detail</span></div><div><b>Five-year warranty</b><span>For lasting peace of mind</span></div><div><b>Complimentary repairs assessment</b><span>Care that continues</span></div></section><section className="quote"><div><p className="eyebrow">The Form Edit</p><blockquote>“A new language of modern adornment.”</blockquote></div><div><div className="stars">★★★★★</div><blockquote>“It feels discovered, not simply bought.”</blockquote><small>Mara L. · verified buyer, Quezon City</small></div></section><Journal/><Newsletter/></main>}

function Categories(){return <section className="categories">{['Rings','Earrings','Necklaces','Bracelets'].map((x,i)=><a href={`/${x.toLowerCase()}`} key={x} className={`category cat-${i}`}><span>{x}</span><b>→</b></a>)}</section>}
function ProductArt({tone}:{tone:string}){return <div className={`product-art ${tone}`}><span/><i/></div>}
function ProductSection({title,kicker,products:addProducts,add,wish,toggleWish}:{title:string,kicker:string,products:Product[],add:(p:Product)=>void,wish:string[],toggleWish:(p:Product)=>void}){return <section className="product-section"><div className="section-heading"><div><p className="eyebrow">{kicker}</p><h2>{title}</h2></div><a href="/shop">View all →</a></div><div className="product-grid">{addProducts.map(p=><article className="product-card" key={p.name}><button className="wish" onClick={()=>toggleWish(p)} aria-label={`${wish.includes(p.name)?'Remove':'Add'} ${p.name} wishlist`}>{wish.includes(p.name)?'♥':'♡'}</button><ProductArt tone={p.tone}/><div className="product-info"><div><h3>{p.name}</h3><p>{p.material}</p><b>{peso(p.price)}</b></div><button onClick={()=>add(p)}>Quick add</button></div></article>)}</div></section>}
function Catalog({title,products:ps,filter,setFilter,sort,setSort,add,wish,toggleWish}:{title:string,products:Product[],filter:string,setFilter:(x:string)=>void,sort:string,setSort:(x:string)=>void,add:(p:Product)=>void,wish:string[],toggleWish:(p:Product)=>void}){return <main id="main"><section className="page-hero"><p className="eyebrow">Jewelry shaped by instinct</p><h1>{title}</h1><p>Thoughtful forms in recycled silver, gold vermeil, solid gold, pearls, and lab-grown diamonds. Delivered nationwide.</p></section><div className="catalog-tools"><div>{['All','Rings','Earrings','Necklaces','Bracelets','Gold vermeil','Recycled silver'].map(x=><button className={filter===x?'active':''} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div><label>Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div>{ps.length?<ProductSection title={`${ps.length} considered forms`} kicker="Ursula edit" products={ps} add={add} wish={wish} toggleWish={toggleWish}/>:<section className="empty"><h2>No pieces match those filters.</h2><button className="button button-primary" onClick={()=>setFilter('All')}>View all pieces</button></section>}<Newsletter/></main>}
function ContentPage({view,title,products:ps,add,wish,toggleWish}:{view:string,title:string,products:Product[],add:(p:Product)=>void,wish:string[],toggleWish:(p:Product)=>void}){if(view==='wishlist')return <main id="main"><section className="page-hero"><p className="eyebrow">Saved for later</p><h1>{title}</h1><p>Sign in to keep your saved pieces across every device.</p></section><ProductSection title="Pieces to consider" kicker="Ursula favorites" products={ps.slice(0,4)} add={add} wish={wish} toggleWish={toggleWish}/></main>;if(view==='checkout')return <main id="main"><section className="checkout"><div><p className="eyebrow">Secure checkout</p><h1>Where should we send it?</h1><div className="checkout-progress"><b>1 Information</b><span>2 Delivery</span><span>3 Payment</span></div><form onSubmit={e=>e.preventDefault()}><label>Email<input type="email" required placeholder="you@example.com"/></label><div className="form-grid"><label>First name<input required/></label><label>Last name<input required/></label></div><label>Philippine address<input required placeholder="House / unit, street, barangay"/></label><div className="form-grid"><label>City<input required/></label><label>Province<input required/></label><label>Postal code<input required/></label></div><button className="button button-primary full">Continue to delivery</button></form></div><aside><p className="eyebrow">Order summary</p><div className="bag-row"><ProductArt tone="silver"/><span>Imprint Ring<small>{peso(9800)}</small></span></div><div className="bag-total"><span>Total</span><b>{peso(9800)}</b></div><p className="microcopy">Free insured nationwide delivery · Taxes included</p></aside></section></main>;
 const copy:Record<string,[string,string[]]>={story:['Ursula creates intimate objects that become part of how you move through the world.',['Born from instinct','Designed in Manila','Made for every expression']],craftsmanship:['Every piece passes through specialist hands—from carving and casting to setting and polishing.',['Small-batch production','Hand-finished surfaces','Five-year warranty']],materials:['We prioritize recycled metals, thoughtful sourcing, durable finishes, and transparent care.',['Recycled precious metals','Lab-grown diamonds','Responsible packaging']],journal:['Notes on material, form, care, and the rituals that make jewelry your own.',['The imperfect stack','Silver after dark','Choosing with meaning']],appointments:['Meet one-to-one with an Ursula stylist online for sizing, gifting, and layering.',['30-minute video call','Personal recommendations','Complimentary service']],personalization:['Build a piece around initials, a date, a private word, or a meaningful stone.',['Engraving from ₱1,200','Selected stones','Preview first']],care:['Simple care preserves surface, shape, and shine for years of daily wear.',['Store separately','Avoid fragrance','Use a soft cloth']],repairs:['Our five-year warranty covers manufacturing faults, with repair care beyond it.',['Photo assessment','Transparent quote','Nationwide return']],shipping:['Secure delivery across Metro Manila and nationwide with tracking.',['Free over ₱8,000','2–4 days Metro Manila','4–8 days provincial']],faq:['Quick guidance on sizing, materials, delivery, personalization, warranty, and returns.',['Are pieces hypoallergenic?','How do I find my size?','Can I return engraving?']],contact:['Speak with client care for product advice, orders, gifts, returns, or repairs.',['Live chat · 10am–7pm PHT','hello@ursulajewelry.com','One-day reply']],account:['Sign in to see orders, saved pieces, addresses, returns, and warranty requests.',['Order tracking','Saved details','Faster checkout']]};const c=copy[view]||['This service is designed with the same care as every piece.',['Personal guidance','Secure and private','Here when needed']];return <main id="main"><section className="editorial-hero"><div><p className="eyebrow">Ursula · Philippines</p><h1>{title}</h1><p>{c[0]}</p><a className="button button-primary" href={view==='account'?'/account/sign-in':view==='appointments'?'/appointments/book':'/contact'}>{view==='account'?'Sign in securely':view==='appointments'?'Book an appointment':'Talk to client care'}</a></div><div className="editorial-image"/></section><section className="feature-three">{c[1].map((x,i)=><div key={x}><span>0{i+1}</span><h2>{x}</h2><p>Clear guidance, thoughtful detail, and support before and after purchase.</p></div>)}</section>{view==='journal'&&<Journal/>}<Newsletter/></main>}
function Journal(){return <section className="journal"><div className="section-heading"><div><p className="eyebrow">The Journal</p><h2>Ways of wearing</h2></div><a href="/journal">Read the journal →</a></div><div className="journal-grid">{['The art of the imperfect stack','Silver after dark','A gift with its own language'].map((x,i)=><a href="/journal" key={x}><div className={`journal-image journal-${i}`}/><p className="eyebrow">Style notes</p><h3>{x}</h3><span>Read more →</span></a>)}</div></section>}
function Newsletter(){const [done,setDone]=useState(false);return <section className="newsletter"><div><p className="eyebrow">Stay close</p><h2>Private previews, new forms, and notes from the studio.</h2></div>{done?<p role="status"><b>You’re on the list.</b><br/>A quiet note will arrive soon.</p>:<form onSubmit={e=>{e.preventDefault();setDone(true)}}><label className="sr-only" htmlFor="email">Email address</label><input id="email" type="email" required placeholder="Email address"/><button>Join the list</button><small>Unsubscribe anytime.</small></form>}</section>}
function Footer(){return <footer><a className="footer-brand" href="/">URSULA<span>Jewelry shaped by instinct.</span></a><div><b>Shop</b><a href="/shop">All jewelry</a><a href="/new">New arrivals</a><a href="/fine-jewelry">Fine jewelry</a><a href="/gift-cards">Gift cards</a></div><div><b>Client care</b><a href="/contact">Contact</a><a href="/shipping">Shipping & returns</a><a href="/care">Jewelry care</a><a href="/repairs">Repairs & warranty</a><a href="/faq">FAQ</a></div><div><b>About</b><a href="/story">Our story</a><a href="/craftsmanship">Craftsmanship</a><a href="/materials">Responsibility</a><a href="/journal">Journal</a></div><div><b>Services</b><a href="/personalization">Personalization</a><a href="/appointments">Styling session</a><a href="/account">Track an order</a></div><div className="footer-bottom"><span>Philippines · PHP</span><span>Privacy · Terms · Accessibility · Cookies</span></div></footer>}
